# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts --production=false && npm cache clean --force

# Copy source code
COPY . .

# Build TypeScript code
RUN npm run build

# Default command for container
CMD ["node", "dist/index.js"]
